import type { Metadata } from "next";
import "./globals.css";
import Script from "next/script";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru">
        <body>
        {children}
        <Script
            src="https://api-maps.yandex.ru/2.1/?apikey=YOUR_KEY&lang=ru_RU"
            strategy="beforeInteractive"
        />
        </body>
        </html>
    );
}
